apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rabbit-producer-1
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rabbit-samples
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: rmq-1
  source:
    git:
      url: https://github.com/sumantrana/scs-rabbitmq-producer.git
      ref:
        branch: main